### ISSUE TITLE
Fronius: interface shows negative values

### ISSUE THREAD

**Issue by foxzqw** [nymea/nymea-plugins#519]
Fronius Solar Inverter / State `Current power`  shows negative values 
all other values are correct

nymea:core 0.29.2+202111021743-buster1
nymea:app 1.0.361

**Comment by t-mon** [comment]
In the details view (showing the raw values) it is intentional negative. 

Within the entire nymea eco system, from device perspective, a negative value means producing power (like inverters, batteries returning energy or meters measuring returning energy), a positive value consuming power. 

Next release (0.30.0) is around the corner introducing the entire energy management, you will see soon why we had to unify this system wide. With the new release you will get much better view on your inverter data.

**Comment by foxzqw** [comment]
thank you for explanation
looking forward for next release 👍
